name: Run Tests on PR

on:
  pull_request:
    branches:
      - main # Triggers on PRs targeting the `main` branch
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Make mvnw executable
      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw

      # Step 5: Run tests
      - name: Run Maven tests
        run: |
          ./mvnw clean test
